### PR TITLE
Fix `ViewportCommand::InnerSize` not resizing viewport on Wayland (#4211)

### LINKED ISSUE #3668: Window ignoring resize request
**Describe the bug**

I was testing something against the current github/master (hash in case it helps with testing: 84a6d6f). I noticed that the code I have for resizing the window is not working against master (but works in 0.24.0).

**To Reproduce**

I resize the window when I load user config files (in my app, the window position and size are saved in different files, bypassing the built in persistence system):

```rs
if let (Some(x), Some(y), Some(width), Some(height)) = (x, y, width, height) {
    ctx.send_viewport_cmd(egui::viewport::ViewportCommand::InnerSize(
        egui::Vec2::new(width, height),
    ));
    ctx.send_viewport_cmd(egui::viewport::ViewportCommand::OuterPosition(
        egui::Pos2::new(x, y),
    ));
}
```

I run this code during `eframe::App::update` because the user can load a config file at any time.

**Expected behavior**

In 0.24.0 (the released version of 0.24 on crates), my window loads with the expected size and position but on the github version, it appears to be giving me the default window dimensions. It's certainly not the ones saved in my settings file.

**Desktop (please complete the following information):**
 - OS: Linux/x11

### LINKED ISSUE #4196: On wayland `ViewportCommand::InnerSize` doesn't update the content size
**Describe the bug**

On wayland (mutter) when the window is resized using `ViewportCommand::InnerSize` the viewport size doesn't match the window.

| Drag Resize Handle | Press "Phone Size" | Drag Resize Handle | Press "Desktop Size" |
| - | - | - | - |
| Screenshot from 2024-03-20 11-30-33 | Screenshot from 2024-03-20 11-28-20 | Screenshot from 2024-03-20 11-30-54 | Screenshot from 2024-03-20 11-28-35 |

I suspect this is because winit doesn't send `Resized` events after the resize, the correct way to handle this is applying the value returned from `request_inner_size` to the viewport here:

https://github.com/emilk/egui/blob/d449cb1d488cbc10915a3c720a232c01c1901561/crates/egui-winit/src/lib.rs#L1313-L1322

**To Reproduce**
1. On gnome shell press the Phone Size button, note the window contents are stretched
2. Resize the window, note the window contents are not stretched
3. Repeat

**Expected behavior**
Contents are not stretched

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39

https://github.com/emilk/egui/pull/4197 makes it easier to test.

### LINKED ISSUE #4259: KDE `ViewportCommand::InnerSize` is undone via instantaneous `WindowEvent::Resized`
**Describe the bug**

When running egui under kde the window cannot be resized programmatically.

This is **not** fixed by https://github.com/emilk/egui/pull/4211 nor https://github.com/emilk/egui/pull/4182.

Here's a truncated annotated `WAYLAND_DEBUG` spew:
```
# The window buffer is created at size 875x597 (wl_buffer@87)
[1863912.251]  -> zwp_linux_buffer_params_v1@85.create_immed(new id wl_buffer@87, 875, 597, 875713112, 0)
# Previous buffer is destroyed
[1863912.694]  -> wl_buffer@61.destroy()
# New buffer (wl_buffer@87) is attached to window
[1863928.273]  -> wl_surface@25.attach(wl_buffer@87, 0, 0)
# Client requests resize to 1280x720
[1871323.978]  -> xdg_surface@26.set_window_geometry(0, 0, 1280, 720)
[1871323.983]  -> wp_viewport@29.set_destination(1280, 720)
[2024-03-28T15:47:08Z INFO  egui_winit] ViewportCommand::InnerSize, not will be delivered later with the [WindowEvent::Resized]
[1871324.007]  -> xdg_toplevel@27.unset_fullscreen()
# New window buffer is created at size 1280x720 (wl_buffer@100)
[1871329.109]  -> zwp_linux_buffer_params_v1@98.create_immed(new id wl_buffer@100, 1280, 720, 875713112, 0)
# Previous buffer is destroyed (wl_buffer@87)
[1871329.698]  -> wl_buffer@87.destroy()
# Compositor requests the client resize to 875x597
[1871330.256] xdg_toplevel@27.configure(875, 597, array[4])
# Client resizes to 875x597
[1871330.318]  -> xdg_surface@26.set_window_geometry(0, 0, 875, 597)
[1871330.323]  -> wp_viewport@29.set_destination(875, 597)
# New window buffer is created at size 875x597 (wl_buffer@109)
[1871334.217]  -> zwp_linux_buffer_params_v1@64.create_immed(new id wl_buffer@109, 875, 597, 875713112, 0)
# Previous buffer is destroyed (wl_buffer@100)
[1871334.574]  -> wl_buffer@100.destroy()
# New buffer (wl_buffer@109) is attached to window
[1871338.805]  -> wl_surface@25.attach(wl_buffer@109, 0, 0)
```

[Full `WAYLAND_DEBUG` log](https://github.com/emilk/egui/files/14792296/egui_noresize.txt)

I think the `xdg_toplevel@27.configure` is becoming a `WindowEvent::Resized` and undoing the resize.
I'm not certain but it could be that the `wl_buffer@87.destroy()` of the currently attached buffer is triggering a configure.

This happens on KDE but not weston or Gnome. The winit example client doesn't exhibit this behaviour.

**To Reproduce**
1. Run KDE
You can launch a nested KDE session via:
```bash
export $(dbus-launch)
kwin_wayland --xwayland --no-lockscreen
```
2. Run the egui demo:
If you're running nested:
```bash
WAYLAND_DEBUG=1 WAYLAND_DISPLAY=wayland-1 cargo run -p egui_demo_app [--features wgpu]
```
3. Resize the window using the "Resize to..." drop-down.
4. Note that the window doesn't change size

**Expected behavior**

Window should resize.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 39 (plasma)

**Additional context**

This was brought to my attention by ruffle developers: https://github.com/ruffle-rs/ruffle/pull/15781

### PR DESCRIPTION
**Pull request by rustbasic**
Issues :
* Closes #3668 
* Related #4078
* Related #4079
* Related #4135 
* Closes #4196 
* Closes #4259 

Pull requests :
* Related #4088
* Closes #4207

### CODE REVIEW

**Comment by ColinKinloch** [comment]
This doesn't fix https://github.com/emilk/egui/issues/4196

The issue is that on wayland when programmatically resizing a window via `request_inner_size` winit (intentionally) won't receive a `Resized` event.

Which means when running under wayland it's appropriate to resize the viewport directly after resizing the window.

**Comment by ColinKinloch** [comment]
Hense why in https://github.com/emilk/egui/pull/4207 I check the size before and after each ViewportCommand is processed and resize the viewport if its changed.

**Comment by rustbasic** [comment]
> Hense why in #4207 I check the size before and after each `ViewportCommand` is processed and resize the viewport if its changed.


Thank you for letting me know the results.

**Comment by rustbasic** [comment]
@emilk

If you don't need it right away, you can close it.

**Comment by rustbasic** [comment]
@ColinKinloch 

I changed this a little more.
Could you try this one more time and let me know the results?

**Comment by ColinKinloch** [comment]
It works!
Thanks for working on this.

I think however that logging "InnerSize ignered by winit" should be something else.
The return values of `request_inner_size` are:
* None: New size will be in a Resized event
* Requested size: The platform has synchronously resized the window
* Unchanged size: The platform has denied the request
* Different size: The platform has chosen a different size (maybe doesn't allow for windows bigger than the monitor)

Maybe only log when the value isn't None or the requested size.

**Comment by rustbasic** [comment]
> Could you try this one more time and let me know the results?

@ColinKinloch 

Could you try one more time to see if the size is saved properly and let me know the results?

**Comment by ColinKinloch** [comment]
I found an issue (https://github.com/emilk/egui/issues/4220) while testing this PR.
It exists in `master` also but I thought I'd mention it here in case there's an easy solution in the scope of this PR.

**Comment by rustbasic** [comment]
Could you try the following and let me know the results?

* #4182

**Comment by ColinKinloch** [comment]
That fixes it, thanks!

**Comment by rustbasic** [comment]
> I found an issue (#4220) while testing this PR. It exists in `master` also but I thought I'd mention it here in case there's an easy solution in the scope of this PR.



> That fixes it, thanks!

thank you, too.

File: crates/eframe/src/native/glow_integration.rs [hunk 1]
```diff
@@ -1198,6 +1198,22 @@ impl GlutinWindowContext {
         self.gl_config.display().get_proc_address(addr)
     }
 
+    #[allow(clippy::needless_pass_by_value)]
+    pub(crate) fn active_viewports_retain(
```
Comment (emilk) [inline crates/eframe/src/native/glow_integration.rs:1202]: maybe

```suggestion
    pub(crate) fn remove_viewports_not_in(
```

File: crates/eframe/src/native/glow_integration.rs [hunk 2]
```diff
@@ -1242,19 +1258,47 @@ impl GlutinWindowContext {
...
                     &mut viewport.screenshot_requested,
                 );
+
+                // For Wayland : https://github.com/emilk/egui/issues/4196
+                if cfg!(target_os = "linux") {
+                    let inner_size = window.inner_size();
+                    if inner_size != save_inner_size {
+                        Self::resize_for_other_os(self, viewport_id, inner_size);
+                    }
+                }
```
Comment (emilk) [inline crates/eframe/src/native/glow_integration.rs:1268]: Why do we need this workaround? Can we fix this bug in `winit` instead of making `eframe` more complicated?

Comment (ColinKinloch) [reply crates/eframe/src/native/glow_integration.rs:1268]: It's a intended and documented behaviour of winit.
In the case that the resize is handled synchronously the new size is returned from `request_inner_size` and no `Resized` event is generated.

File: crates/egui-winit/src/lib.rs [hunk 3]
```diff
@@ -1310,11 +1344,14 @@ fn process_viewport_command(
...
             let width_px = pixels_per_point * size.x.max(1.0);
             let height_px = pixels_per_point * size.y.max(1.0);
-            if window
-                .request_inner_size(PhysicalSize::new(width_px, height_px))
-                .is_some()
+            if let Some(_inner_size) =
+                window.request_inner_size(PhysicalSize::new(width_px, height_px))
             {
-                log::debug!("ViewportCommand::InnerSize ignored by winit");
+                log::info!("ViewportCommand::InnerSize ignored by winit");
```
Comment (ColinKinloch) [inline crates/egui-winit/src/lib.rs:1350]: I don't like this log message.

Would it make sense to pass the current viewport size into `process_viewport_command`?

It would allow for a more accurate message.
Also adding `resize_requested: &mut bool` and comparing sizes on `InnerSize` might preferable to comparing the before and after viewport size for every group of commands.

Comment (rustbasic) [reply crates/egui-winit/src/lib.rs:1350]: This is to support both `glow` and `wgpu`.

**Comment by ColinKinloch** [comment]
I just tested this with `RUST_BACKTRACE=1 cargo run -p egui_demo_app --features "wgpu"`
Resizing with the dropdown gives:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target/debug/egui_demo_app`
[2024-03-25T14:49:56Z INFO  eframe] Both the glow and wgpu renderers are available. Using wgpu.
[2024-03-25T14:49:56Z INFO  egui_wgpu] There were 3 available wgpu adapters: {backend: Vulkan, device_type: IntegratedGpu, name: "AMD Radeon Graphics (RADV GFX1103_R1)", driver: "radv", driver_info: "Mesa 23.3.6", vendor: 0x1002, device: 0x15BF}, {backend: Vulkan, device_type: Cpu, name: "llvmpipe (LLVM 17.0.6, 256 bits)", driver: "llvmpipe", driver_info: "Mesa 23.3.6 (LLVM 17.0.6)", vendor: 0x10005}, {backend: Gl, device_type: Other, name: "AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 17.0.6, DRM 3.57, 6.7.10-200.fc39.x86_64)", vendor: 0x1002}
[2024-03-25T14:50:00Z INFO  egui_winit] ViewportCommand::InnerSize ignored by winit
thread 'main' panicked at 'already borrowed: BorrowMutError', crates/eframe/src/native/wgpu_integration.rs:1120:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
   3: core::result::Result<T,E>::expect
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1033:23
   4: core::cell::RefCell<T>::borrow_mut
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/cell.rs:1017:9
   5: eframe::native::wgpu_integration::resize_for_other_os
             at ./crates/eframe/src/native/wgpu_integration.rs:1120:26
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rustbasic** [comment]
> I just tested this with `RUST_BACKTRACE=1 cargo run -p egui_demo_app --features "wgpu"` Resizing with the dropdown gives:


Could you try running the modifications you made now and let me know the results?

**Comment by ColinKinloch** [comment]
No real change:
```diff
< thread 'main' panicked at 'already borrowed: BorrowMutError', crates/eframe/src/native/wgpu_integration.rs:1120:33
> thread 'main' panicked at 'already borrowed: BorrowMutError', crates/eframe/src/native/wgpu_integration.rs:1118:33
```

**Comment by ColinKinloch** [comment]
Is the issue these two existing at the same time?
https://github.com/emilk/egui/blob/7cab92dd36a1400c3a3f4a589861e69ca480804d/crates/eframe/src/native/wgpu_integration.rs#L982
https://github.com/emilk/egui/blob/7cab92dd36a1400c3a3f4a589861e69ca480804d/crates/eframe/src/native/wgpu_integration.rs#L1118

**Comment by rustbasic** [comment]
> Is the issue these two existing at the same time?

It has been modified. Please let me know the results, and I will check the results tomorrow.

**Comment by ColinKinloch** [comment]
It's fixed! 🎉

**Comment by rustbasic** [comment]
> It's fixed! 🎉

thank you.

**Comment by emilk** [comment]
Does this fix https://github.com/emilk/egui/issues/3668 ?

**Comment by rustbasic** [comment]
> Does this fix #3668 ?

This alone is expected to fix #3668.

**Comment by emilk** [comment]
Since you are still pushing new commits I assume this is not ready for review yet

**Comment by rustbasic** [comment]
It's completed.

**Comment by rustbasic** [comment]
> Since you are still pushing new commits I assume this is not ready for review yet

It's completed.

File: crates/egui-winit/src/lib.rs [hunk 4]
```diff
@@ -1310,11 +1327,17 @@ fn process_viewport_command(
...
             {
-                log::debug!("ViewportCommand::InnerSize ignored by winit");
+                // ex) linux
+                log::info!("ViewportCommand::InnerSize, not will be delivered later with the [WindowEvent::Resized]");
+
+                info.inner_rect = math_inner_rect(window, Some(pixels_per_point));
+                info.outer_rect = math_outer_rect(window, Some(pixels_per_point));
+            } else {
+                // ex) Windows, MacOS
+                log::info!("ViewportCommand::InnerSize, will be delivered later with the [WindowEvent::Resized]");
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:1340]: When `request_inner_size` returns `None`, it worked as it should, so we shouldn't log anything (or log it at `trace`)

File: crates/egui-winit/src/lib.rs [hunk 5]
```diff
@@ -865,70 +865,85 @@ impl State {
...
-    viewport_info: &mut ViewportInfo,
-    egui_ctx: &egui::Context,
-    window: &Window,
-) {
-    crate::profile_function!();
+pub fn math_inner_rect(window: &Window, pixels_per_point: Option<f32>) -> Option<Rect> {
+    let pixels_per_point = match pixels_per_point {
+        Some(pixels_per_point) => pixels_per_point,
+        None => window.scale_factor() as f32,
+    };
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:872]: This is never called with `None`, so let's simplify

```suggestion
pub fn math_inner_rect(window: &Window, pixels_per_point: f32) -> Option<Rect> {
```

File: crates/egui-winit/src/lib.rs [hunk 6]
```diff
@@ -865,70 +865,85 @@ impl State {
...
-    let outer_pos_px = if has_a_position {
-        window
-            .outer_position()
-            .map(|pos| Pos2::new(pos.x as f32, pos.y as f32))
-            .ok()
-    } else {
-        None
-    };
+    inner_rect_px.map(|r| r / pixels_per_point)
+}
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:891]: You can simplify this code by early-outing with `?` (it works on `Option` too)

File: crates/egui-winit/src/lib.rs [hunk 7]
```diff
@@ -865,70 +865,85 @@ impl State {
...
-/// Update the given viewport info with the current state of the window.
-///
-/// Call before [`State::take_egui_input`].
-pub fn update_viewport_info(
-    viewport_info: &mut ViewportInfo,
-    egui_ctx: &egui::Context,
-    window: &Window,
-) {
-    crate::profile_function!();
+pub fn math_inner_rect(window: &Window, pixels_per_point: Option<f32>) -> Option<Rect> {
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:868]:
```suggestion
pub fn inner_rect_in_points(window: &Window, pixels_per_point: Option<f32>) -> Option<Rect> {
```

File: crates/egui-winit/src/lib.rs [hunk 8]
```diff
@@ -865,70 +865,85 @@ impl State {
...
-    let inner_size_px = if has_a_position {
-        let size = window.inner_size();
-        Some(Vec2::new(size.width as f32, size.height as f32))
-    } else {
-        None
+pub fn math_outer_rect(window: &Window, pixels_per_point: Option<f32>) -> Option<Rect> {
+    let pixels_per_point = match pixels_per_point {
+        Some(pixels_per_point) => pixels_per_point,
+        None => window.scale_factor() as f32,
     };
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:897]:
```suggestion
pub fn outer_rect_in_points(window: &Window, pixels_per_point: f32) -> Option<Rect> {
```

File: crates/egui-winit/src/lib.rs [hunk 9]
```diff
@@ -865,70 +865,85 @@ impl State {
...
         let size = window.outer_size();
-        Some(Vec2::new(size.width as f32, size.height as f32))
+        Some(egui::Vec2::new(size.width as f32, size.height as f32))
+    };
+
+    let outer_rect_px = if let (Some(pos), Some(size)) = (outer_pos_px, outer_size_px) {
+        Some(egui::Rect::from_min_size(pos, size))
     } else {
         None
     };
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:913]: Same here; simplify with `?`

File: crates/egui-winit/src/lib.rs [hunk 10]
```diff
@@ -1310,11 +1327,17 @@ fn process_viewport_command(
...
             let height_px = pixels_per_point * size.y.max(1.0);
-            if window
-                .request_inner_size(PhysicalSize::new(width_px, height_px))
-                .is_some()
+            if let Some(_inner_size) =
+                window.request_inner_size(PhysicalSize::new(width_px, height_px))
             {
-                log::debug!("ViewportCommand::InnerSize ignored by winit");
+                // ex) linux
+                log::info!("ViewportCommand::InnerSize, not will be delivered later with the [WindowEvent::Resized]");
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:1334]: This should be `debug!` or `trace!` log level to reduct log spam.

File: crates/egui-winit/src/lib.rs [hunk 11]
```diff
@@ -1310,11 +1327,17 @@ fn process_viewport_command(
...
+
+                info.inner_rect = math_inner_rect(window, Some(pixels_per_point));
+                info.outer_rect = math_outer_rect(window, Some(pixels_per_point));
```
Comment (emilk) [inline crates/egui-winit/src/lib.rs:1337]: From the docs of `request_inner_size`:

> On platforms where the size is entirely controlled by the user the applied size will be returned immediately, resize event in such case may not be generated.
> On platforms where resizing is disallowed by the windowing system, the current inner size is returned immidiatelly, and the user one is ignored.

Your code seems to assume we're in the first case, i.e. that the size was applied, but we won't be getting any resized events.

We should check if we're not in the second case. If the returned size is the same as the one we passed to `request_inner_size`, then we're in the first case. If not, we're in the second (and should just log a warning or something).

File: crates/egui-winit/src/lib.rs (hunk 10 above)
Comment (emilk) [inline crates/egui-winit/src/lib.rs:1334]:
```suggestion
                log::trace!("ViewportCommand::InnerSize, WindowEvent::Resized won't be delivered. Assuming the resize worked.");
```

File: crates/eframe/src/native/glow_integration.rs [hunk 12]
```diff
@@ -980,8 +980,7 @@ impl GlutinWindowContext {
         if let Some(window) = &window {
             viewport_from_window.insert(window.id(), ViewportId::ROOT);
             window_from_viewport.insert(ViewportId::ROOT, window.id());
-            info.minimized = window.is_minimized();
-            info.maximized = Some(window.is_maximized());
+            egui_winit::update_viewport_info(&mut info, egui_ctx, window);
```
Comment (emilk) [inline crates/eframe/src/native/glow_integration.rs:983]: `update_viewport_info` doesn't assign `minimized` and `maximized` on Mac (because it's not always safe to do so without a deadlock).

Maybe we could add a `bool` argument to `update_viewport_info` indicating wether or not it is safe to read `minimized` and `maximized` on mac? (it is safe to do during startup, but not from within the even loop)

File: crates/eframe/src/native/glow_integration.rs [hunk 13]
```diff
@@ -1246,19 +1261,29 @@ impl GlutinWindowContext {
...
+        self.remove_viewports_not_in(viewport_output);
+    }
+
+    fn resize_for_other_os(
+        &mut self,
+        viewport_id: ViewportId,
+        inner_size: winit::dpi::PhysicalSize<u32>,
+    ) {
+        self.resize(viewport_id, inner_size);
     }
```
Comment (emilk) [inline crates/eframe/src/native/glow_integration.rs:1287]: Unnecessary function. Just inline it at the call site.

File: crates/eframe/src/native/glow_integration.rs [hunk 14]
```diff
@@ -1237,6 +1250,8 @@ impl GlutinWindowContext {
             );
 
             if let Some(window) = &viewport.window {
+                let save_inner_size = window.inner_size();
```
Comment (emilk) [inline crates/eframe/src/native/glow_integration.rs:1253]:
```suggestion
                let old_inner_size = window.inner_size();
```

File: crates/eframe/src/native/glow_integration.rs [hunk 15]
```diff
@@ -1202,6 +1201,22 @@ impl GlutinWindowContext {
...
+        let active_viewports_ids: ViewportIdSet = viewport_output.keys().copied().collect();
+
+        // GC old viewports
+        self.viewports
+            .retain(|id, _| active_viewports_ids.contains(id));
+        self.viewport_from_window
+            .retain(|_, id| active_viewports_ids.contains(id));
+        self.window_from_viewport
+            .retain(|id, _| active_viewports_ids.contains(id));
+    }
```
Comment (emilk) [inline crates/eframe/src/native/glow_integration.rs:1218]:
```suggestion
    pub(crate) fn remove_viewports_not_in(
        &mut self,
        viewport_output: &ViewportIdMap<ViewportOutput>,
    ) {
        // GC old viewports
        self.viewports
            .retain(|id, _| viewport_output.contains_key(id));
        self.viewport_from_window
            .retain(|_, id| viewport_output.contains_key(id));
        self.window_from_viewport
            .retain(|id, _| viewport_output.contains_key(id));
    }
```

File: crates/eframe/src/native/wgpu_integration.rs [hunk 16]
```diff
@@ -1016,14 +1016,38 @@ fn render_immediate_viewport(
...
+    painter: &mut egui_wgpu::winit::Painter,
+    viewport_from_window: &mut HashMap<WindowId, ViewportId>,
+    viewport_output: ViewportIdMap<ViewportOutput>,
+) {
+    let active_viewports_ids: ViewportIdSet = viewport_output.keys().copied().collect();
+
+    // Prune dead viewports:
+    viewports.retain(|id, _| active_viewports_ids.contains(id));
+    viewport_from_window.retain(|_, id| active_viewports_ids.contains(id));
+    painter.gc_viewports(&active_viewports_ids);
```
Comment (emilk) [inline crates/eframe/src/native/wgpu_integration.rs:1041]: Just inline this at the call site instead (like it was). This is just unnecessary.

File: crates/eframe/src/native/wgpu_integration.rs [hunk 17]
```diff
@@ -1051,6 +1075,8 @@ fn handle_viewport_output(
         );
 
         if let Some(window) = viewport.window.as_ref() {
+            let save_inner_size = window.inner_size();
```
Comment (emilk) [inline crates/eframe/src/native/wgpu_integration.rs:1078]:
```suggestion
            let old_inner_size = window.inner_size();
```

File: crates/eframe/src/native/wgpu_integration.rs [hunk 18]
```diff
@@ -1060,8 +1086,33 @@ fn handle_viewport_output(
                 is_viewport_focused,
                 &mut viewport.screenshot_requested,
             );
+
+            // For Wayland : https://github.com/emilk/egui/issues/4196
+            if cfg!(target_os = "linux") {
+                let inner_size = window.inner_size();
+                if inner_size != save_inner_size {
+                    resize_for_other_os(painter, &viewport_id, inner_size);
```
Comment (emilk) [inline crates/eframe/src/native/wgpu_integration.rs:1094]:
```suggestion
                let new_inner_size = window.inner_size();
                if new_inner_size != save_inner_size {
                    resize_for_other_os(painter, &viewport_id, new_inner_size);
```

File: crates/eframe/src/native/wgpu_integration.rs [hunk 19]
```diff
@@ -1060,8 +1086,33 @@ fn handle_viewport_output(
...
+    inner_size: winit::dpi::PhysicalSize<u32>,
+) {
+    use std::num::NonZeroU32;
+
+    if let (Some(width), Some(height)) = (
+        NonZeroU32::new(inner_size.width),
+        NonZeroU32::new(inner_size.height),
+    ) {
+        painter.on_window_resized(*viewport_id, width, height);
+    }
```
Comment (emilk) [inline crates/eframe/src/native/wgpu_integration.rs:1115]: inline

**Review by emilk — CHANGES_REQUESTED** [review]
Thanks for working on this!

File: crates/eframe/src/native/wgpu_integration.rs (hunk 16 above)
Comment (rustbasic) [reply crates/eframe/src/native/wgpu_integration.rs:1041]: > Just inline this at the call site instead (like it was). This is just unnecessary.

This `remove_viewports_not_in()` may be called elsewhere in the future.

File: crates/egui-winit/src/lib.rs (hunk 6 above)
Comment (rustbasic) [reply crates/egui-winit/src/lib.rs]: > You can simplify this code by early-outing with `?` (it works on `Option` too)

This is the method I mainly use for readability, so please have emilk edit this part if necessary.

File: crates/egui-winit/src/lib.rs (hunk 4 above)
Comment (rustbasic) [reply crates/egui-winit/src/lib.rs:1316]: > When `request_inner_size` returns `None`, it worked as it should, so we shouldn't log anything (or log it at `trace`)

Yes, this part will only be logged when Some().

**Comment by rustbasic** [comment]
I'm completed.

**Comment by rustbasic** [comment]
I'm completed.

calling `process_viewport_commands()`,
Unified with `handle_viewport_output()`.

**Comment by rustbasic** [comment]
I'm completed.

calling `process_viewport_commands()`, Unified with `handle_viewport_output()`.

**Comment by emilk** [comment]
I'll finish this up

**Review by emilk — APPROVED** [review]
