### PR TITLE
Fix: panic when dragging window between monitors of different pixels_per_point

### LINKED ISSUE #4178: There is on very rare occasions a case where a panic occurred
There is on very rare occasions a case where a panic occurred at line 2,132 of context.rs when a Viewport exit.
( On screens with different pixels_per_point. )

### LINKED ISSUE #4179: There is on very rare occasions a case where a panic occurred at line 152 of layers.rs
There is on very rare occasions a case where a panic occurred at line 152 of layers.rs when a Viewport exit.
( At this time, self.0.len() == 0 )

( On screens with different pixels_per_point. )

thread 'main' panicked at C:\prog\egui\crates\egui\src\layers.rs:152:15:
index out of bounds: the len is 0 but the index is 0

### PR DESCRIPTION
**Pull request by rustbasic**
Fix: panic when dragging window between monitors of different pixels_per_point

This will continue to help us as we develop `egui`.
I hope you agree with my defense of `panic`.

* Related #3959
* Related #4088

* Closes #4178
* Closes #4179

There is also a way to add log if necessary.
```
                log::debug!("Anti-panic behavior occurs");
```

### CODE REVIEW

File: crates/egui/src/layers.rs [hunk 1]
```diff
@@ -153,6 +153,12 @@ impl PaintList {
     /// and then later setting it using `paint_list.set(idx, cr, frame);`.
     #[inline(always)]
     pub fn set(&mut self, idx: ShapeIdx, clip_rect: Rect, shape: Shape) {
+        if self.0.len() <= idx.0 {
+            #[cfg(feature = "log")]
+            log::warn!("Index {} is out of bounds for PaintList", idx.0);
+            self.add(clip_rect, Shape::Noop);
```
Comment (emilk) [inline crates/egui/src/layers.rs:159]:
```suggestion
            return;
```

File: crates/egui/src/context.rs [hunk 2]
```diff
@@ -2418,12 +2418,14 @@ impl Context {
 
         self.write(|ctx| {
             let tessellation_options = ctx.memory.options.tessellation_options;
-            let texture_atlas = ctx
-                .fonts
-                .get(&pixels_per_point.into())
+            let texture_atlas = if let Some(fonts) = ctx.fonts.get(&pixels_per_point.into()) { fonts.texture_atlas() } else {
```
Comment (emilk) [inline crates/egui/src/context.rs:2421]:
```suggestion
            let texture_atlas = if let Some(fonts) = ctx.fonts.get(&pixels_per_point.into()) {
            	fonts.texture_atlas()
           	} else {
```

File: crates/egui/src/context.rs [hunk 3]
```diff
@@ -2418,12 +2418,14 @@ impl Context {
...
+                #[cfg(feature = "log")]
+                log::warn!("No font size matching {pixels_per_point} pixels per point found.");
+                ctx.fonts.iter().next()
                 .expect("tessellate called with a different pixels_per_point than the font atlas was created with. \
-                         You should use egui::FullOutput::pixels_per_point when tessellating.")
-                .texture_atlas();
+                You should use egui::FullOutput::pixels_per_point when tessellating.")
```
Comment (emilk) [inline crates/egui/src/context.rs:2426]: This error message is wrong now, it should be "No fonts loaded"

**Review by emilk — CHANGES_REQUESTED** [review]

**Review by emilk — APPROVED** [review]
