### PR TITLE
Fix `Ui::scroll_with_delta` only scrolling if the `ScrollArea` is focused

### LINKED ISSUE #2783: `scroll_with_delta` doesn't work
**Describe the bug**

`scroll_with_delta` doesn't seem to work.

**To Reproduce**

1. Create an app with `eframe`.
2. Copy the `scroll_with_delta` example from documentation.
3. Click `Scroll down` button.
4. See that nothing happens.

```rust
use eframe::egui::{self, Vec2};

fn main() -> Result<(), eframe::Error> {
    eframe::run_native(
        "My egui App",
        eframe::NativeOptions::default(),
        Box::new(|_cc| Box::new(MyApp {})),
    )
}

struct MyApp {}

impl eframe::App for MyApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            let mut scroll_delta = Vec2::ZERO;
            if ui.button("Scroll down").clicked() {
                scroll_delta.y -= 64.0; // move content up
            }
            egui::ScrollArea::vertical().show(ui, |ui| {
                ui.scroll_with_delta(scroll_delta);
                for i in 0..1000 {
                    ui.label(format!("Item {}", i));
                }
            });
        });
    }
}
```

**Expected behavior**

Content scrolls down.

**Screenshots**

[video](https://user-images.githubusercontent.com/12128106/222928092-28c4f85e-29e7-4b11-9992-f4811a4c41ad.webm)

**Desktop (please complete the following information):**

 - OS: GNU/Linux

### PR DESCRIPTION
**Pull request by lucasmerlin**
This introduces the boolean field force_current_scroll_area to InputState which will be set when scroll_with_delta is called, causing the ScrollArea to skip the check whether it is focused and always consume the smooth scroll delta.

* Closes #2783 
* Related to #4295

### CODE REVIEW

File: crates/egui/src/ui.rs [hunk 1]
```diff
@@ -1091,8 +1091,10 @@ impl Ui {
     /// # });
     /// ```
     pub fn scroll_with_delta(&self, delta: Vec2) {
-        self.ctx()
-            .input_mut(|input| input.smooth_scroll_delta += delta);
+        self.ctx().input_mut(|input| {
+            input.smooth_scroll_delta += delta;
+            input.force_current_scroll_area = true;
```
Comment (emilk) [inline crates/egui/src/ui.rs:1096]: I think a better fix is to add a `scroll_delta` to `FrameState`, alongside `FrameState::scroll_target`

Comment (lucasmerlin) [reply crates/egui/src/ui.rs]: That is indeed much nicer 👍 I've updated my PR

File: crates/egui/src/frame_state.rs [hunk 2]
```diff
@@ -38,9 +38,12 @@ pub(crate) struct FrameState {
     /// Initialized to `None` at the start of each frame.
     pub(crate) tooltip_state: Option<TooltipFrameState>,
 
-    /// horizontal, vertical
+    /// The current scroll area should scroll to this range (horizontal, vertical).
     pub(crate) scroll_target: [Option<(Rangef, Option<Align>)>; 2],
 
+    /// The current scroll area should scroll by this much (horizontal, vertical).
+    pub(crate) scroll_delta: [Option<f32>; 2],
```
Comment (emilk) [inline crates/egui/src/frame_state.rs:45]: This could just be a `Vec2`, no?

```suggestion
    pub(crate) scroll_delta: Vec2,
```

Comment (lucasmerlin) [reply crates/egui/src/frame_state.rs]: Updated. I think we could also update scroll_target to be `Option<[(..); 2]>` instead of `[Option<(..)>; 2]`. That would make the code in Prepared::end a bit cleaner. Should I include that change as well?

Comment (emilk) [reply crates/egui/src/frame_state.rs]: No - keep each PR as small as possible please

File: crates/egui/src/ui.rs [hunk 3]
```diff
@@ -1091,8 +1091,9 @@ impl Ui {
     /// # });
     /// ```
     pub fn scroll_with_delta(&self, delta: Vec2) {
-        self.ctx()
-            .input_mut(|input| input.smooth_scroll_delta += delta);
+        self.ctx().frame_state_mut(|state| {
+            state.scroll_delta = delta;
```
Comment (emilk) [inline crates/egui/src/ui.rs:1095]: Are we sure we don't want `+=` here? In either case, we should document that behavior.

**Review by emilk — APPROVED** [review]

File: crates/egui/src/ui.rs (hunk 3 above)
Comment (lucasmerlin) [reply crates/egui/src/ui.rs]: I changed it to +=, I think that makes more sense. Also documented the behavior.

**Review by lucasmerlin — COMMENTED** [review]
I also noticed I accidentally inverted the behavior of scroll_with_delta, this is fixed now

File: crates/egui/src/ui.rs [hunk 4]
```diff
@@ -1073,6 +1073,8 @@ impl Ui {
     /// A positive Y-value indicates the content is being moved down,
     /// as when swiping down on a touch-screen or track-pad with natural scrolling.
     ///
+    /// If this is called multiple times per frame for the same [`ScrollArea`], the deltas will be combined.
```
Comment (emilk) [inline crates/egui/src/ui.rs:1076]:
```suggestion
    /// If this is called multiple times per frame for the same [`ScrollArea`], the deltas will be summed.
```

File: crates/egui_demo_lib/src/demo/scrolling.rs [hunk 5]
```diff
@@ -292,6 +293,9 @@ impl super::View for ScrollTo {
         ui.horizontal(|ui| {
             scroll_top |= ui.button("Scroll to top").clicked();
             scroll_bottom |= ui.button("Scroll to bottom").clicked();
+            if ui.button("Scroll down by 64px").clicked() {
+                scroll_delta = Some(Vec2::new(0.0, -64.0));
```
Comment (emilk) [inline crates/egui_demo_lib/src/demo/scrolling.rs:297]:
```suggestion
                scroll_delta = Some(64.0 * Vec2::UP); // move contents up
```

File: crates/egui_demo_lib/src/demo/scrolling.rs [hunk 6]
```diff
@@ -292,6 +293,9 @@ impl super::View for ScrollTo {
         ui.horizontal(|ui| {
             scroll_top |= ui.button("Scroll to top").clicked();
             scroll_bottom |= ui.button("Scroll to bottom").clicked();
+            if ui.button("Scroll down by 64px").clicked() {
```
Comment (emilk) [inline crates/egui_demo_lib/src/demo/scrolling.rs:296]: It would be nicer demo with two buttons, using ⬆⬇ arrows instead of the text (egui supports those emojis)

**Review by emilk — APPROVED** [review]
nice!

File: crates/egui_demo_lib/src/demo/scrolling.rs (hunk 6 above)
Comment (lucasmerlin) [reply crates/egui_demo_lib/src/demo/scrolling.rs]: Done. Like this?

https://github.com/emilk/egui/assets/8009393/1b8663f5-b06d-4a13-a10a-9041fb4f011c

**Review by emilk — APPROVED** [review]
