### PR TITLE
Fix tooltips overlapping widgets (#566)

### LINKED ISSUE #566: Tooltip covers widgets at the bottom of drawable area
Hi!

If a widget is placed at the bottom of the drawable area (`TopBottomPanel::bottom` for example), the tooltip covers the widget on hover:

Screen Shot 2021-07-16 at 11 21 04

Screen Shot 2021-07-16 at 11 21 13

A separate issue is that some widgets have default tooltips that cannot be disabled (see #548)

### PR DESCRIPTION
**Pull request by rekka**
This is a fix to an issue where tooltips would cover the corresponding widget if it is near the bottom of the drawable area (#566).

Now if a tooltip does not fit under the widget, it will be placed above it.

## Before (demo app, hovering over link `https://docs.rs/egui` at the bottom of Widget Gallery)

Screen Shot 2021-07-18 at 19 27 45

## After

Screen Shot 2021-07-18 at 19 25 33
Screen Shot 2021-07-18 at 19 26 22

## Notes:

- Adds code to keep track of the sizes of all tooltips to `popup::MonoState`.
- The number of tooltips displayed in the current frame is tracked in `FrameState::tooltip_rect`
- I didn't want to break pub api, so I added a new private function `containers::popup::show_tooltip_at_avoid`.

(I couldn't run `./sh/check.sh` since it fails on some unrelated code in `egui/src/widgets/plot/items.rs:92:46`. No idea why.)

Closes #566

### CODE REVIEW

**Comment by rekka** [comment]
The commit is basically ready for review, but I'll wait until the workflow runs...

**Comment by rekka** [comment]
I have fixed the conflict caused by commit 224af23fd. I hope you can consider merging this.

**Comment by emilk** [comment]
> (I couldn't run `./sh/check.sh` since it fails on some unrelated code in `egui/src/widgets/plot/items.rs:92:46`. No idea why.)

Could you elaborate on this? What is the failure? Perhaps open an issue on it?

File: egui/src/frame_state.rs [hunk 1]
```diff
@@ -24,7 +24,7 @@ pub(crate) struct FrameState {
     /// If a tooltip has been shown this frame, where was it?
     /// This is used to prevent multiple tooltips to cover each other.
     /// Initialized to `None` at the start of each frame.
-    pub(crate) tooltip_rect: Option<(Id, Rect)>,
+    pub(crate) tooltip_rect: Option<(Id, Rect, usize)>,
```
Comment (emilk) [inline egui/src/frame_state.rs:27]: This should have a comment describing the new tuple field

**Review by emilk — APPROVED** [review]
Nice!
