### PR TITLE
Fix wrong gamma in WebkitGTK

### LINKED ISSUE #794: Everything is super dark in epiphany
**Describe the bug**
The demo web app is super dark in epiphany. See screenshot below.

**To Reproduce**
1. Open the [demo web app](https://emilk.github.io/egui/index.html) in epiphany.

**Expected behavior**
Should look like it does in other web browsers (e.g. Firefox).

**Screenshots**
Screenshot from 2021-10-13 10-49-04

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Browser: Epiphany
 - Version: 40.3

### PR DESCRIPTION
**Pull request by t18b219k**
Epiphany's incorrect sRGB handling  cause  same result as displaying linear image on other browsers.
I fixed this issue by double sRGB correcting in post process. 
Glitched image
color difference
fixed result
スクリーンショット 2021-11-08 174650

### CODE REVIEW

File: egui_web/src/webgl1.rs [hunk 1]
```diff
@@ -591,7 +592,19 @@ impl PostProcess {
 
         gl.bind_texture(Gl::TEXTURE_2D, None);
         gl.bind_framebuffer(Gl::FRAMEBUFFER, None);
-
+        // currently epiphany only support webgl1
+        let epiphany_workaround = if web_sys::window()
```
Comment (emilk) [inline egui_web/src/webgl1.rs:596]: let's call this `frag_shader_prefix` instead

File: egui_glow/CHANGELOG.md [hunk 2]
```diff
@@ -3,6 +3,7 @@ All notable changes to the `egui_glow` integration will be noted in this file.
 
 
 ## Unreleased
+* Add `workarounds` to `Painter::new` to pass GLSL macro to fix platform specific behavior.
```
Comment (emilk) [inline egui_glow/CHANGELOG.md:6]:
```suggestion
```

Since this isn't a generally usable thing (you need to also modify the shaders), I think we can omit it from this changelog

**Review by emilk — CHANGES_REQUESTED** [review]

File: egui_glow/src/painter.rs [hunk 3]
```diff
@@ -61,18 +61,33 @@ impl Painter {
...
     /// # Errors
     /// will return `Err` below cases
     /// * failed to compile shader
     /// * failed to create postprocess on webgl with `sRGB` support
     /// * failed to create buffer
-    pub fn new(gl: &glow::Context, pp_fb_extent: Option<[i32; 2]>) -> Result<Painter, String> {
+    pub fn new(
+        gl: &glow::Context,
+        pp_fb_extent: Option<[i32; 2]>,
+        workarounds: &[String],
```
Comment (emilk) [inline egui_glow/src/painter.rs:75]: I think just calling this `shader_prefix: &str` here and elsewhere would be clearer

**Review by emilk — CHANGES_REQUESTED** [review]

**Comment by t18b219k** [comment]
I made some mistake in diag VAO code .
So i want to fix this issue in this PR.

File: egui_web/src/glow_wrapping.rs [hunk 4]
```diff
@@ -15,10 +16,17 @@ pub(crate) struct WrappedGlowPainter {
...
+            console_log("Enabling epiphany workaround");
+            "#define EPIPHANY_WORKAROUND"
+        } else {
+            ""
+        };
         let canvas = canvas_element_or_die(canvas_id);
         let gl_ctx = init_glow_context_from_canvas(&canvas);
         let dimension = [canvas.width() as i32, canvas.height() as i32];
-        let painter = egui_glow::Painter::new(&gl_ctx, Some(dimension))
+        let painter = egui_glow::Painter::new(&gl_ctx, Some(dimension), epiphany_wr)
```
Comment (emilk) [inline egui_web/src/glow_wrapping.rs:29]: I was wondering if an alternative work-around would work as well: to turn off the `postprocessing` step on epiphany.

So something like:


``` rust
let pp_fb_extents = if user_agent.contains("Epiphany") {
     None // epiphany doesn't support sRGB blending even with render-to-texture
} else {
    Some(dimensions);
};
let painter = egui_glow::Painter::new(&gl_ctx, pp_fb_extents);
```

Did you try this already?

Comment (t18b219k) [reply egui_web/src/glow_wrapping.rs:29]: if we disable post process produce not good image in Epiphany.
スクリーンショット 2021-11-10 203714
Epiphany does not

Comment (t18b219k) [reply egui_web/src/glow_wrapping.rs:29]: I also tested midori and konqueror .
midori produce same result with epiphany so this issue from webkitGTK implementation.
texture sRGB worked but frame buffer sRGB incorrect.

Comment (t18b219k) [reply egui_web/src/glow_wrapping.rs:29]: I'm tuning color correcting.
and found `vec4(pow(gl_FragColor.rgb,vec3(1.0/2.2)),gl_FragColor.a)`is better than double apply.

Comment (t18b219k) [reply egui_web/src/glow_wrapping.rs:29]: we can detect WebkitGTK by following checks.
*  webgl unmasked vendor Apple
*  webgl renderer WebKit WebGL
*  user-agent not "Mac OS X"

File: egui_glow/src/misc_util.rs [hunk 5]
```diff
@@ -197,7 +197,7 @@ pub(crate) unsafe fn need_to_emulate_vao(gl: &glow::Context) -> bool {
         ));
         if version_str.contains("1.0") {
             //need to test OES_vertex_array_object .
-            gl.supported_extensions()
+            !gl.supported_extensions()
```
Comment (emilk) [inline egui_glow/src/misc_util.rs:200]: easy mistake to make. I think it would be less confusing if the function would be called `supports_vao`. As written, it leads to double-negatives like this.

File: egui_web/CHANGELOG.md [hunk 6]
```diff
@@ -4,7 +4,8 @@ All notable changes to the `egui_web` integration will be noted in this file.
 
 
 ## Unreleased
-*Add feature `glow` to switch to a [`glow`](https://github.com/grovesNL/glow) based painter ([#868](https://github.com/emilk/egui/pull/868)).
+* fix [Everything super dark in epiphany](https://github.com/emilk/egui/issues/794) for webgl1 and glow based painter
```
Comment (emilk) [inline egui_web/CHANGELOG.md:7]:
```suggestion
* Fix [dark rendering in epiphany](https://github.com/emilk/egui/issues/794) for WebGL1 and glow based painter ([#888](https://github.com/emilk/egui/pull/888/)).
```

**Review by emilk — APPROVED** [review]

File: egui_glow/src/misc_util.rs (hunk 5 above)
Comment (t18b219k) [reply egui_glow/src/misc_util.rs:200]: Ok i fixed it.
