### PR TITLE
Fix cursor clipping in `TextEdit` inside a `ScrollArea`

### LINKED ISSUE #1531: ScrollArea scroll state modified by sibling textedit
**Describe the bug**
If I add a text edit, then a scroll area, typing in the text edit moves the position of the scroll area.
E.g.
scroll_on_text_entry

**To Reproduce**
Sample program...
```
use eframe::egui::{self, ScrollArea};

fn main() {
    let native_options = eframe::NativeOptions::default();
    eframe::run_native("My egui App", native_options, Box::new(|cc| Box::new(MyEguiApp::new(cc))));
}

#[derive(Default)]
struct MyEguiApp {
    input: String,
}

impl MyEguiApp {
    fn new(cc: &eframe::CreationContext<'_>) -> Self {
        // Customize egui here with cc.egui_ctx.set_fonts and cc.egui_ctx.set_visuals.
        // Restore app state using cc.storage (requires the "persistence" feature).
        // Use the cc.gl (a glow::Context) to create graphics shaders and buffers that you can use
        // for e.g. egui::PaintCallback.
        Self::default()
    }
}

impl eframe::App for MyEguiApp {
   fn update(&mut self, ctx: &egui::Context, frame: &mut eframe::Frame) {
       egui::CentralPanel::default().show(ctx, |ui| {
           ui.text_edit_singleline(&mut self.input);
           ScrollArea::vertical()
               .show(ui, |ui| {
                   for i in 0..100 {
                       ui.label(format!("test{}", i));
                   }
               });
       });
   }
}
```

**Expected behavior**
Scroll area stays fixed when typing in adjacent boxes

**Desktop (please complete the following information):**
 - OS: Linux, observed on both Ubuntu 20.04 and Arch Linux

**Additional context**
* Typing when the text edit is not selected does not move the scroll area
* I tried a few workarounds thinking that it might be related to internal state from the text edit leaking into the scroll area
    * Adding id sources to the text edit or the scroll area didn't seem to help
    * Wrapping the text edit within a sub-ui with ui.allocate_rect also doesn't resolve the issue

### PR DESCRIPTION
**Pull request by juancampa**
* Closes #1531

### Before
Notice how the cursor hides after third enter and when the line is long.

https://github.com/user-attachments/assets/8e45736e-d6c7-4dc6-94d0-213188c199ff

### After
Cursor is always visible

https://github.com/user-attachments/assets/43200683-3524-471b-990a-eb7b49385fa9

 - `ScrollArea` now checks if there's a `scroll_target` in `begin`, if there is, it saves it because it's not from its children, then restore it in `end`.
 - `TextEdit` now allocates additional space if its galley grows during the frame. This is needed so that any surrounding `ScrollArea` can bring the cursor to view, otherwise the cursor lays outside the the `ScrollArea`'s `content_ui`.

### CODE REVIEW

**Comment by juancampa** [comment]
The reason for this fix btw is because the temporary workaround #153 (cc @Barugon) has a problem. Notice that on the fourth `Enter` press, the scrollarea doesn't follow the cursor. That's because the ScrollArea doesn't set up a clip rect (because contents are small enough) and the text area doesn't know it's been clipped.

https://github.com/emilk/egui/assets/1410520/1d38827a-4110-4d3a-ac09-7cc45167af2a

File: crates/egui/src/containers/scroll_area.rs [hunk 1]
```diff
@@ -751,6 +761,13 @@ impl Prepared {
             }
         }
 
+        // Restore scroll target (if any) meant for ScrollAreas up the stack
+        if saved_scroll_target[0].is_some() || saved_scroll_target[1].is_some() {
+            ui.ctx().frame_state_mut(|state| {
+                state.scroll_target = saved_scroll_target;
```
Comment (emilk) [inline crates/egui/src/containers/scroll_area.rs:767]: If either the horizontal or the vertical part of `saved_scroll_target` is set, overwrite both.
If neither is set, overwrite neither.

Without having thought deeply about this, this seems wrong to me.

Why not always write to `state.scroll_target`?
Or why not do the logic per dimension?

Comment (juancampa) [reply crates/egui/src/containers/scroll_area.rs]: I changed it to be per dimension since it's more readable. I was trying to prevent locking twice but probably not worth it

Comment (juancampa) [reply crates/egui/src/containers/scroll_area.rs]: We could also _always_ restore the saved scroll target, a few extra cycles but not worth worrying about. Let me know and I can change it.

File: crates/egui/src/containers/scroll_area.rs [hunk 2]
```diff
@@ -752,6 +762,15 @@ impl Prepared {
             }
         }
 
+        // Restore scroll target (if any) meant for ScrollAreas up the stack
+        for d in 0..2 {
+            if saved_scroll_target[d].is_some() {
+                ui.ctx().frame_state_mut(|state| {
```
Comment (emilk) [inline crates/egui/src/containers/scroll_area.rs:768]: avoid locking twice

```suggestion
        ui.ctx().frame_state_mut(|state| {
            for d in 0..2 {
                if saved_scroll_target[d].is_some() {
```

File: crates/egui/src/widgets/text_edit/builder.rs [hunk 3]
```diff
@@ -671,8 +671,7 @@ impl<'t> TextEdit<'t> {
                     let primary_cursor_rect =
                         cursor_rect(galley_pos, &galley, &cursor_range.primary, row_height);
 
-                    let is_fully_visible = ui.clip_rect().contains_rect(rect); // TODO: remove this HACK workaround for https://github.com/emilk/egui/issues/1531
-                    if (response.changed || selection_changed) && !is_fully_visible {
+                    if response.changed || selection_changed {
```
Comment (emilk) [inline crates/egui/src/widgets/text_edit/builder.rs:674]: Nice to get rid of this hack! Can we get rid of it in `crates/egui/src/text_selection/label_text_selection.rs` too?

**Comment by juancampa** [comment]
@emilk I just reimplemented this on top of the latest `master`. Also posted two videos in the description showing the issue.

File: crates/egui/src/containers/scroll_area.rs [hunk 4]
```diff
@@ -499,6 +499,11 @@ struct Prepared {
 
     scrolling_enabled: bool,
     stick_to_end: Vec2b,
+
+    /// If there was a scroll target before the ScrollArea was added this frame, it's
+    /// not for us to handle so we save it and restore it after this ScrollArea is done.
+    saved_scroll_target: [Option<pass_state::ScrollTarget>; 2],
```
Comment (lucasmerlin) [inline crates/egui/src/containers/scroll_area.rs:505]: There is also `FrameState::scroll_delta`, I think we should do the same with that?

**Review by lucasmerlin — APPROVED** [review]
Looks good to me!

File: crates/egui/src/containers/scroll_area.rs (hunk 4 above)
Comment (juancampa) [reply crates/egui/src/containers/scroll_area.rs:505]: @lucasmerlin There's no `FrameState` anymore so I think this comment is not valid anymore?

**Review by juancampa — COMMENTED** [review]
@emilk this should be ready to merge unless there's more feedback.

**Comment by emilk** [comment]
thanks!

**Comment by IaVashik** [comment]
This change breaks `TextEdit::singleline` when it's used outside of a `ScrollArea`. The added `ui.allocate_rect` call causes incorrect horizontal expansion because it allocates extra space based on the formatted text size, which is not appropriate for single-line text edits. This logic should be implemented in `ScrollArea` instead of `TextEdit`. `ScrollArea` should handle the cursor visibility, as it already manages its content's position and size. Imo, `TextEdit` shouldn't have to alter its size for `ScrollArea` to work correctly.

**Comment by IaVashik** [comment]
Also, I haven't been able to reproduce this bug in the current version, *but only when I remove the code from lines 726-734 in `builder.rs`*.  Do we actually need this code at all?
