### PR TITLE
fix egui-wgpu callback viewport size check (#3759)

### LINKED ISSUE #3759: Viewport out-of-range when first constructing certain UIs rendered with egui-wgpu callbacks
**Describe the bug**

Viewport out-of-range, causing a validation error, when first constructing certain UIs rendered with egui-wgpu callbacks.
This only happens on the first frame, the fix would simply be skipping the callback and set viewport command when the viewport rect is outside of the display.

**To Reproduce**
1. Make a Bottom panel with a scroll area inside
2. Add egui-wgpu Callbacks to it

**Expected behavior**
The item to be skipped if the viewport is outside of display.

**Additional context**
https://github.com/automancy/automancy/blob/main/src/bin/automancy/gui/tile_selection.rs

(Remove the following from the code to actually get the panic:
```rs
        if !ui.ctx().screen_rect().contains_rect(rect) {
            continue;
        }
```
)

### PR DESCRIPTION
**Pull request by msparkles**
Closes #3759

### CODE REVIEW

File: crates/egui-wgpu/src/renderer.rs [hunk 1]
```diff
@@ -450,39 +450,35 @@ impl Renderer {
                         continue;
                     };
 
-                    if callback.rect.is_positive() {
```
Comment (emilk) [inline crates/egui-wgpu/src/renderer.rs:453]: Shouldn't we check `callback.rect.is_positive()` too?

Comment (emilk) [reply crates/egui-wgpu/src/renderer.rs:453]: oh right, nevermind

**Review by emilk — APPROVED** [review]
